### ISSUE TITLE
Is this expression correct? It looks wrong..

### ISSUE THREAD

**Issue by cculianu** [sipa/bitcoin-seeder#107]
https://github.com/sipa/bitcoin-seeder/blob/4ff7d8f3bb4bfe8268b573005281019c18809e1e/db.cpp#L53

Seems to me `ignoreTill`'s intention is to ignore a node until some timepoint in the future. This expression appears to .. have the condition inverted, and only ignore nodes with `ignoreTill` in the past, and not ignore them if `ignoreTill` is in the future..

**Comment by sipa** [comment]
I believe you're right that the reverse was actually what I intended (12 years ago...), but having tested the change, I don't think it's actually desirable. It results in a growing number of newly discovered IPs remaining uninvestigated. It's probably better to remove this "ignore" logic entirely (the "ban" logic is more powerful and seems to function just fine).

**Comment by cculianu** [comment]
Ah that makes sense. Thanks for responding.
