### ISSUE TITLE
dnsseed does not get multiple addr from Bitcoin 0.12.0+

### ISSUE THREAD

**Issue by schinzelh** [sipa/bitcoin-seeder#37]
It seems that something in the Bitcoin protocol for version 0.12.0+ has changed in such a way that the dnsseeder only gets a single addr (AdvertiseLocal) from a node it connects to.

I have forced dnsseed to connect to specific nodes with version 0.11.2, 0.12.0 and 0.12.1 and dnsseed only got multiple addr from 0.11.2 while 0.12.0/0.12.1 simply closed the connection after sending one node.

This is the output while connecting to a 0.11.2 node

```
Starting seeder...done
Starting 96 crawler threads...done
[16-05-31 18:18:19] 0/1 available (0 tried in 1464711499s, 0 new, 1 active), 0 banned; 0 DNS requests, 4 db queries
5.196.75.28:8333      : SEND version
5.196.75.28:8333      : RECV version
5.196.75.28:8333      : SEND verack
5.196.75.28:8333      : done processing version
5.196.75.28:8333      : RECV verack
5.196.75.28:8333      : version 70002
5.196.75.28:8333      : SEND getaddr
5.196.75.28:8333      : done processing verack
5.196.75.28:8333      : RECV ping
5.196.75.28:8333      : done processing ping
5.196.75.28:8333      : RECV addr
5.196.75.28:8333      : got 1000 addresses
5.196.75.28:8333      : got address 37.233.101.132:8333
5.196.75.28:8333      : added address 37.233.101.132:8333 (#0)
[...]2000 lines removed [...]
5.196.75.28:8333      : got address 104.200.151.89:8333
5.196.75.28:8333      : added address 104.200.151.89:8333 (#129)
5.196.75.28:8333      : done processing addr
5.196.75.28:8333: GOOD!!!
```

And this is the output while connecting to a 0.12.x node

```
Starting seeder...done
Starting 96 crawler threads...done
[16-05-31 18:28:10] 0/1 available (0 tried in 1464712090s, 0 new, 1 active), 0 banned; 0 DNS requests, 4 db queries
95.170.95.133:8333    : SEND version
95.170.95.133:8333    : RECV version
95.170.95.133:8333    : SEND verack
95.170.95.133:8333    : done processing version
95.170.95.133:8333    : RECV verack
95.170.95.133:8333    : version 70012
95.170.95.133:8333    : SEND getaddr
95.170.95.133:8333    : done processing verack
95.170.95.133:8333    : RECV ping
95.170.95.133:8333    : done processing ping
95.170.95.133:8333    : RECV addr
95.170.95.133:8333    : got 1 addresses
95.170.95.133:8333    : got address 95.170.95.133:8333
95.170.95.133:8333    : added address 95.170.95.133:8333 (#1)
95.170.95.133:8333    : done processing addr
95.170.95.133:8333: GOOD!!!
```

As you can see it only gets one entry: the one it has connected to (AdvertiseLocal).

**Comment by UdjinM6** [comment]
I think I found the reason. Node 0.11 is broadcasting its address to every other node once a day https://github.com/bitcoin/bitcoin/blob/0.11/src/main.cpp#L5001-L5017 and node 0.12 is broadcasting itself to every node right after this node is connected https://github.com/bitcoin/bitcoin/blob/0.12/src/main.cpp#L5652-L5657. So connected node (crawler in this case) receives `addr` from 0.12 node even without asking for it. I guess crawler confuses this self-advertisement `addr` with the `getaddr` answer now. Bitcoin Core nodes are fine btw, they keep connection and will receive `getaddr` answer after `pto->nNextAddrSend` timeout.

**Comment by sipa** [comment]
So the solution would be waiting until an addr arrives with more than 1
entry, I guess?

**Comment by schinzelh** [comment]
@UdjinM6 that makes a lot of sense, dnsseed is just processing one addr message per node and then moves to the next

@sipa maybe it's better to wait for another addr response if the first only contained the self advertisement of the node?

**Comment by UdjinM6** [comment]
@sipa I'm not very familiar with crawler code tbh, I think combination @schinzelh 's idea is better i.e. if first `addr` has single entry and this entry is the same as `you` -> wait for only one more `addr`, no matter how many entries there are. Otherwise you could stuck forever if some node always sends you single entry only (for whatever reason).

**Comment by sipa** [comment]
See #38.
