### ISSUE TITLE
bitcoin-seeder not listening on IPv4

### ISSUE THREAD

**Issue by mdrankin** [sipa/bitcoin-seeder#49]
My fork of bitcoin-seeder is no longer working, but ti did initially. Upon troubleshooting I can see that it is not listening on IPv4, only IPv6. As my VPS only runs IPv4 I'm pretty sure this is why it's stopped working.

Is there a way to force it to only listen on IPv4?

[root@160398 ~]# netstat -nlp |grep 53
udp6       0      0 :::53                   :::*                                150/./dnsseed

**Comment by mdrankin** [comment]
I'm not 100% certain that it should show up under netstat -nlp, however I certainly can't get it to work any more. See https://bitcointalk.org/index.php?topic=2310316

**Comment by jonasschnelli** [comment]
Can it be that you don't have the rights to bind to port 53 (not sure if this would only affect IPv4). Can you try with -p 5353?

**Comment by mdrankin** [comment]
It was an issue with my set up. It's working, just doesn't advertise that it's listening on port 53.
