### ISSUE TITLE
Does not listen port 53

### ISSUE THREAD

**Issue by jkman2** [sipa/bitcoin-seeder#51]
Fresh Lbuntu 17.10 install in Virtual box. No error on compilation.

I run
sudo ./dnsseed -h dnsseed -n localhost -m test. -p 53
...
Starting 4 DNS threads for dnsseed on localhost (port 53).......done
...

but
nslookup dnsseed localhost
;; connection timed out; no server could be reached

**Comment by jkman2** [comment]
This is where it stops.
ssize_t insize = recvmsg(listenSocket, &msg, 0);

**Comment by jonasschnelli** [comment]
Does the same happen if you run non sudo on port 5353?
Can you attach gdb and get a strack trace?

**Comment by jkman2** [comment]
UDP port 5353 is already in use. TCP port 5353 is closed.
_netcat -z -v -u localhost 5353
Connection to localhost 5353 port [udp/mdns] succeeded!_

If I use port 5555 or 50 dnsseed opens that UDP port.

Port 50 works with sudo.
_netcat -z -v -u localhost 50
Connection to localhost 50 port [udp/re-mail-ck] succeeded!_

UFW is inactive.
_sudo ufw status
Status: inactive_

Iptables is empty.

I don't know is I got the log right but here it is.

` sudo ./backtrace.sh 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Supporting whitelisted filters: 0x1,0x5,0x9,0xd
Loading dnsseed.dat...done
Starting 4 DNS threads for dnsseed on localhost (port 53).......done
Starting seeder...done
Starting 96 crawler threads...done
[17-12-06 11:35:18] 1632/110666 available (76203 tried in 63249s, 32927 new, 1536 active), 0 banned; 0 DNS requests, 0 db queries^C
Program received signal SIGINT, Interrupt.
0x00007fea113b68b4 in __GI___poll (fds=0x55a9d2ceb260, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
29	../sysdeps/unix/sysv/linux/poll.c: No such file or directory.

Thread 1 (Thread 0x7fea12100080 (LWP 3369)):
#0  0x00007fea113b68b4 in __GI___poll (fds=0x55a9d2ceb260, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007fea116990f4 in ?? () from /usr/lib/sudo/libsudo_util.so.0
#2  0x00007fea11692495 in sudo_ev_loop_v1 () from /usr/lib/sudo/libsudo_util.so.0
#3  0x000055a9d147a8ec in ?? ()
#4  0x000055a9d1477781 in ?? ()
#5  0x000055a9d1484912 in ?? ()
#6  0x000055a9d14762cf in ?? ()
#7  0x00007fea112cf1c1 in __libc_start_main (main=0x55a9d1474aa0, argc=10, argv=0x7ffef0d6b668, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffef0d6b658) at ../csu/libc-start.c:308
#8  0x000055a9d147676a in ?? ()
`

**Comment by jkman2** [comment]
I need to learn how to use GDB.

**Comment by jkman2** [comment]
systemd-resolved is added to Ubuntu 16.10 ->. 127.0.0.53:53 causes problems.

I think bitcoin seeder need to be binded to use only specified IP address like '-b 10.0.2.15'.
