### ISSUE TITLE
Does not work on ipv4 address

### ISSUE THREAD

**Issue by albabosh** [sipa/bitcoin-seeder#59]
Seeder does not listen on ipv4 address, it works on ipv6 only.

**Comment by jonasschnelli** [comment]
Can you give us a bit more about your environment?
How do you start your seeder (arguments)?
Give us some logs?
Have you tried `dig AAAA <yourseed>` and `did A <yourseed>` from a remote host?

**Comment by albabosh** [comment]
sudo ./dnsseed -h seed.myhost.com -n seedns.myhost.com -m support@myhost.com -t 2 -d 1
Supporting whitelisted filters: 0x1,0x5,0x9,0xd
Loading dnsseed.dat...done
Starting 1 DNS threads for seed.myhost.com on seedns.myhost.com (port 53)....done
Starting seeder...done
Starting 2 crawler threads...done
[18-01-31 01:57:41] 0/1 available (1 tried in 10s, 0 new, 0 active), 0 banned; 0 DNS requests, 0 db queries


sudo netstat -tunlp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name

tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      314/sshd
tcp        0      0 0.0.0.0:25              0.0.0.0:*               LISTEN      466/master
tcp6       0      0 :::25                   :::*                    LISTEN      466/master
udp6       0      0 :::53                   :::*                                6934/dnsseed

**Comment by theicosuperman** [comment]
Same situation
sudo ./dnsseed -h btcz.ps-pool.ru -n 188.40.135.251 -m antoneguru@gmail.com -p 5353 
also tried with 53 port

Supporting whitelisted filters: 0x1,0x5,0x9,0xd
Using IPv4 proxy at 188.40.135.251:53
[18-04-16 15:40:06] 38/27624 available (25942 tried in 1272s, 146 new, 1536 active), 31 banned; 0 DNS requests, 0 db queries
Starting seeder...done
Starting 96 crawler threads...done
[18-04-16 15:34:40] 54/27519 available (25897 tried in 1802s, 86 new, 1536 active), 6 banned; 0 DNS reque

netstat -apn | grep dnsseed 
tcp6       0      1 2a01:4f8:221:1e47:60522 2001:0:9d38:78cf:2:8233 SYN_SENT    17116/dnsseed   
tcp6       0      1 2a01:4f8:221:1e47:53878 2a02:587:280a:f400:8233 SYN_SENT    17116/dnsseed   
tcp6       0      1 2a01:4f8:221:1e47:41114 2601:246:4000:a2:8:8233 SYN_SENT    17116/dnsseed   
tcp6       0      1 2a01:4f8:221:1e47:39728 2601:644:2:8130:46:8233 SYN_SENT    17116/dnsseed   
tcp6       0      1 2a01:4f8:221:1e47:34462 2001:0:9d38:6ab8:1:8233 SYN_SENT    17116/dnsseed   
tcp6       0      1 2a01:4f8:221:1e47:35392 2001:0:9d38:6ab8:c:8233 SYN_SENT    17116/dnsseed   
tcp6       0      1 2a01:4f8:221:1e47:36868 2001:1c04:2505:fd0:1989 SYN_SENT    17116/dnsseed   
tcp6       0      1 2a01:4f8:221:1e47:47256 2002:189b:e3c2:0:1:8233 SYN_SENT    17116/dnsseed   
tcp6       0      1 2a01:4f8:221:1e47:33748 2a02:2698:6822:f04:8233 SYN_SENT    17116/dnsseed   
tcp6       0      1 2a01:4f8:221:1e47:37344 2601:243:c00:144f::8233 SYN_SENT    17116/dnsseed   
tcp6       0      1 2a01:4f8:221:1e47:59138 2001:0:9d38:6ab8:c:8233 SYN_SENT    17116/dnsseed   
tcp6       0      1 2a01:4f8:221:1e47:47772 2001:0:9d38:6ab8:1:8233 SYN_SENT    17116/dnsseed   
tcp6       0      1 2a01:4f8:221:1e47:50618 2a02:2f01:5020:a78:8233 SYN_SENT    17116/dnsseed   
tcp6       0      1 2a01:4f8:221:1e47:53556 2001:0:9d38:953c:2:8233 SYN_SENT    17116/dnsseed   
tcp6       0      1 2a01:4f8:221:1e47:59348 2001:0:9d38:6ab8:2:8233 SYN_SENT    17116/dnsseed   
tcp6       0      1 2a01:4f8:221:1e47:53106 2001:0:9d38:6ab8:1:8233 SYN_SENT    17116/dnsseed   
tcp6       0    131 2a01:4f8:221:1e47:50366 2001:0:9d38:6abd:2:8888 ESTABLISHED 17116/dnsseed   
tcp6       0      1 2a01:4f8:221:1e47:49570 2001:0:9d38:6abd:1:1989 SYN_SENT    17116/dnsseed   
tcp6       0      1 2a01:4f8:221:1e47:39494 2001:0:9d38:6abd:4:8233 SYN_SENT    17116/dnsseed   
tcp6       0      1 2a01:4f8:221:1e47:40468 2001:0:9d38:6ab8:2:8233 SYN_SENT    17116/dnsseed   
tcp6       0      1 2a01:4f8:221:1e47:41748 2001:0:9d38:6ab8:6:8233 SYN_SENT    17116/dnsseed   
tcp6       0      1 2a01:4f8:221:1e47:57886 2001:0:9d38:6ab8:2:8888 SYN_SENT    17116/dnsseed   
tcp6       0      1 2a01:4f8:221:1e47:37652 2001:0:5ef5:79fb:1:8233 SYN_SENT    17116/dnsseed   
tcp6       0      1 2a01:4f8:221:1e47:57732 2001:0:9d38:90d7:1:8233 SYN_SENT    17116/dnsseed   
tcp6       0      1 2a01:4f8:221:1e47:47566 2001:0:9d38:90d7:1:8233 SYN_SENT    17116/dnsseed   
tcp6       0      1 2a01:4f8:221:1e47:56268 2001:0:5ef5:79fb:3:8233 SYN_SENT    17116/dnsseed   
tcp6       0      1 2a01:4f8:221:1e47:36686 2001:0:5ef5:79fb:2:1989 SYN_SENT    17116/dnsseed   
tcp6       0      1 2a01:4f8:221:1e47:42604 2a02:2698:1823:ca9:8233 SYN_SENT    17116/dnsseed   
tcp6       0      1 2a01:4f8:221:1e47:50456 2001:0:9d38:90d7:1:8233 SYN_SENT    17116/dnsseed   
tcp6       0      1 2a01:4f8:221:1e47:36732 2001:569:7ba7:2a00:8233 SYN_SENT    17116/dnsseed   
tcp6       0      1 2a01:4f8:221:1e47:44952 2001:0:9d38:6ab8:1:8233 SYN_SENT    17116/dnsseed   
tcp6       0      1 2a01:4f8:221:1e47:38894 2001:0:9d38:6ab8:1:8233 SYN_SENT    17116/dnsseed   
tcp6       0      1 2a01:4f8:221:1e47:49140 2001:0:4137:9e76:2:1989 SYN_SENT    17116/dnsseed   
tcp6       0      1 2a01:4f8:221:1e47:52840 2001:470:d:1355::b:8233 SYN_SENT    17116/dnsseed   
tcp6       0      1 2a01:4f8:221:1e47:44202 2a02:17d0:559:e000:8233 SYN_SENT    17116/dnsseed   
tcp6       0      1 2a01:4f8:221:1e47:33382 2001:0:9d38:6ab8:2:8233 SYN_SENT    17116/dnsseed   
tcp6       0      1 2a01:4f8:221:1e47:43808 2604:5500:3133:ff0:8233 SYN_SENT    17116/dnsseed   
tcp6       0      1 2a01:4f8:221:1e47:57418 2001:0:9d38:78cf:3:8233 SYN_SENT    17116/dnsseed   
tcp6       0      1 2a01:4f8:221:1e47:58062 2001:0:9d38:90d7:3:1989 SYN_SENT    17116/dnsseed   
tcp6       0      1 2a01:4f8:221:1e47:47526 2001:0:9d38:6ab8:3:8233 SYN_SENT    17116/dnsseed   
tcp6       0      1 2a01:4f8:221:1e47:57988 2001:0:9d38:6ab8:1:8233 SYN_SENT    17116/dnsseed   
tcp6       0      1 2a01:4f8:221:1e47:47968 2001:0:9d38:6ab8:8:8233 SYN_SENT    17116/dnsseed   
tcp6       0      1 2a01:4f8:221:1e47:34324 2001:0:9d38:953c:1:8233 SYN_SENT    17116/dnsseed   
tcp6       0      1 2a01:4f8:221:1e47:47500 2001:0:9d38:6abd:8:8233 SYN_SENT    17116/dnsseed   
tcp6       0      1 2a01:4f8:221:1e47:54256 2001:0:9d38:6abd:1:8233 SYN_SENT    17116/dnsseed   
tcp6       0      1 2a01:4f8:221:1e47:45634 2001:0:4137:9e76:1:8233 SYN_SENT    17116/dnsseed   
tcp6       0      1 2a01:4f8:221:1e47:43480 2a02:120b:2c2c:ad8:8233 SYN_SENT    17116/dnsseed   
tcp6       0      1 2a01:4f8:221:1e47:57534 2001:0:9d38:6ab8:3:8233 SYN_SENT    17116/dnsseed   
tcp6       0      1 2a01:4f8:221:1e47:40162 2001:0:5ef5:79fb:c:8233 SYN_SENT    17116/dnsseed   
tcp6       0      1 2a01:4f8:221:1e47:35154 2001:0:9d38:6ab8:1:8233 SYN_SENT    17116/dnsseed   
tcp6       0      1 2a01:4f8:221:1e47:35516 2001:0:9d38:953c:1:8233 SYN_SENT    17116/dnsseed   
tcp6       0      0 2a01:4f8:221:1e47:47914 2001:0:9d38:90d7:1:8233 ESTABLISHED 17116/dnsseed   
tcp6       0      1 2a01:4f8:221:1e47:56948 2a02:587:6805:df00:8233 SYN_SENT    17116/dnsseed   
tcp6       0      1 2a01:4f8:221:1e47:50034 2620:9b::1943:3ea9:1989 SYN_SENT    17116/dnsseed   
tcp6       0      1 2a01:4f8:221:1e47:37606 2001:0:9d38:6ab8:3:8233 SYN_SENT    17116/dnsseed   
tcp6       0      1 2a01:4f8:221:1e47:41956 2001:0:9d38:953c:3:8233 SYN_SENT    17116/dnsseed   
tcp6       0      1 2a01:4f8:221:1e47:56908 2001:0:9d38:90d7:1:8144 SYN_SENT    17116/dnsseed   
tcp6       0      1 2a01:4f8:221:1e47:46474 2001:4c50:14c:cc00:8233 SYN_SENT    17116/dnsseed   
tcp6       0      1 2a01:4f8:221:1e47:37666 2001:569:be84:e100:8233 SYN_SENT    17116/dnsseed   
tcp6       0      1 2a01:4f8:221:1e47:51700 2001:0:4137:9e76:3:8233 SYN_SENT    17116/dnsseed   
tcp6       0      1 2a01:4f8:221:1e47:53006 2001:16b8:6859:bd0:8144 SYN_SENT    17116/dnsseed   
tcp6       0      1 2a01:4f8:221:1e47:57626 2600:1700:7e01:17c:8233 SYN_SENT    17116/dnsseed   
tcp6       0      1 2a01:4f8:221:1e47:42550 2001:0:5ef5:79fb:3:8233 SYN_SENT    17116/dnsseed   
tcp6       0      1 2a01:4f8:221:1e47:35888 2001:0:9d38:6ab8:3:1989 SYN_SENT    17116/dnsseed   
tcp6       0      1 2a01:4f8:221:1e47:33364 2001:0:9d38:6ab8:2:8233 SYN_SENT    17116/dnsseed   
tcp6       0      1 2a01:4f8:221:1e47:56976 2001:0:4137:9e76:c:1989 SYN_SENT    17116/dnsseed   
tcp6       0      1 2a01:4f8:221:1e47:42774 2001:0:9d38:953c:3:8233 SYN_SENT    17116/dnsseed   
tcp6       0      1 2a01:4f8:221:1e47:42108 2001:0:9d38:6abd:2:8233 SYN_SENT    17116/dnsseed   
tcp6       0      1 2a01:4f8:221:1e47:36972 2600:1702:1b70:511:8233 SYN_SENT    17116/dnsseed   
tcp6       0      1 2a01:4f8:221:1e47:53058 2001:0:9d38:6ab8:c:8233 SYN_SENT    17116/dnsseed   
tcp6       0      1 2a01:4f8:221:1e47:39730 2001:0:9d38:6ab8:6:8233 SYN_SENT    17116/dnsseed   
tcp6       0      1 2a01:4f8:221:1e47:44508 2001:0:5ef5:79fd:3:8233 SYN_SENT    17116/dnsseed   
tcp6       0      1 2a01:4f8:221:1e47:42376 2001:0:9d38:78cf:1:8233 SYN_SENT    17116/dnsseed   
tcp6       0      1 2a01:4f8:221:1e47:35580 2001:0:9d38:90d7:3:8233 SYN_SENT    17116/dnsseed   
tcp6       0      1 2a01:4f8:221:1e47:43062 2405:9800:b910:81c:8233 SYN_SENT    17116/dnsseed   
tcp6       0      1 2a01:4f8:221:1e47:54948 2001:0:5ef5:79fd:2:8233 SYN_SENT    17116/dnsseed   
tcp6       0      1 2a01:4f8:221:1e47:36740 2001:0:9d38:90d7:1:8233 SYN_SENT    17116/dnsseed   
tcp6       0      1 2a01:4f8:221:1e47:57008 2406:e001:2061:1:4:8144 SYN_SENT    17116/dnsseed   
tcp6       0      1 2a01:4f8:221:1e47:44434 2001:0:9d38:78cf:1:8233 SYN_SENT    17116/dnsseed   
tcp6       0      1 2a01:4f8:221:1e47:49020 2601:203:c101:afa3:8144 SYN_SENT    17116/dnsseed   
tcp6       0      1 2a01:4f8:221:1e47:45872 2001:0:9d38:78cf:8:8233 SYN_SENT    17116/dnsseed   
tcp6       0      1 2a01:4f8:221:1e47:50068 2601:601:827f:e7d0:8233 SYN_SENT    17116/dnsseed   
tcp6       0      1 2a01:4f8:221:1e47:36608 2001:0:9d38:90d7:1:1989 SYN_SENT    17116/dnsseed   
tcp6       0      1 2a01:4f8:221:1e47:58332 2601:ce:8200:55a9::8233 SYN_SENT    17116/dnsseed   
tcp6       0      1 2a01:4f8:221:1e47:40096 2001:0:9d38:6abd:8:1989 SYN_SENT    17116/dnsseed   
tcp6       0      1 2a01:4f8:221:1e47:35584 2002:4b69:5b8f:1:5:8808 SYN_SENT    17116/dnsseed   
tcp6       0      1 2a01:4f8:221:1e47:36138 2001:0:5ef5:79fb:3:8233 SYN_SENT    17116/dnsseed   
tcp6       0      1 2a01:4f8:221:1e47:53342 2601:500:c200:c8f::8233 SYN_SENT    17116/dnsseed   
tcp6       0      1 2a01:4f8:221:1e47:47284 2001:0:4137:9e76:e:8233 SYN_SENT    17116/dnsseed   
tcp6       0      1 2a01:4f8:221:1e47:60402 2600:1700:8c60:9f6:8233 SYN_SENT    17116/dnsseed   
tcp6       0      1 2a01:4f8:221:1e47:49428 2001:0:9d38:953c:3:8233 SYN_SENT    17116/dnsseed   
tcp6       0      1 2a01:4f8:221:1e47:42256 2001:420:44b1:1250:8233 SYN_SENT    17116/dnsseed   
tcp6       0      1 2a01:4f8:221:1e47:54140 2001:0:9d38:6ab8:1:8233 SYN_SENT    17116/dnsseed   
tcp6       0      1 2a01:4f8:221:1e47:48974 2601:186:4400:d01b:1989 SYN_SENT    17116/dnsseed   
udp6       0      0 :::53                   :::*                                17116/dnsseed   

telnet to 188.40.135.251:53
Trying 188.40.135.251...
telnet: Unable to connect to remote host: Connection refused

;btcz.ps-pool.ru.               IN      ANY

;; ANSWER SECTION:
btcz.ps-pool.ru.        3199    IN      NS      ns1.firstvds.ru.
btcz.ps-pool.ru.        3199    IN      NS      ns2.firstvds.ru.
btcz.ps-pool.ru.        3199    IN      MX      10 mail.btcz.ps-pool.ru.
btcz.ps-pool.ru.        3199    IN      MX      20 mail.btcz.ps-pool.ru.
btcz.ps-pool.ru.        3199    IN      TXT     "v=spf1 ip4:62.109.19.129 a mx ~all"
btcz.ps-pool.ru.        3199    IN      SOA     ps-pool.ru. root.steelbi4.fvds.ru. 2018041200 3600 3600 604800 86400
btcz.ps-pool.ru.        3199    IN      A       188.40.135.251

;; ADDITIONAL SECTION:
mail.btcz.ps-pool.ru.   3199    IN      A       188.40.135.251

**Comment by MasterKungfu** [comment]
how to fix it.

**Comment by CryptoCatOkiOKi** [comment]
Does anyone find a solution here? I have the same issue.

**Comment by cryptorex** [comment]
I've pulled in this PR and it binds to an ipv4 but the protocol is upd6 in netstat, does that matter?

`udp6       0      0 XXX.XXX.202.159:53       :::*                                7176/dnsseed`

**Comment by sipa** [comment]
That shouldn't be a problem; you can bind an IPv6 socket to an IPv4 address. Does it work or not?

**Comment by cryptorex** [comment]
@sipa well, the seeder runs but its a new instance so I'm guessing it will take awhile to crawl for nodes and index them....

**Comment by cryptorex** [comment]
Just to follow up - I've let the seeder run using `-a IPv4_ADDRESS_HERE` and its working and responding to dig A requests with no issues.

It does still bind to the IPv6 socket, but as mentioned above, it does work.
