### ISSUE TITLE
Seeds nodes on different port

### ISSUE THREAD

**Issue by lukepighetti** [sipa/bitcoin-seeder#67]
I set up a sipa seeder and it is grabbing peers from a different coin that uses a different p2p port. Any recommendations for solving this?

**Comment by sipa** [comment]
This software only supports Bitcoin and Bitcoin testnet.

**Comment by lukepighetti** [comment]
Thanks for the reply. I see that sipa is standard dnsseed for altcoins. For that reason I am trying to use it on an altcoin.

Any help would be appreciated.
