### ISSUE TITLE
DNS requests being received but not answered with a corrrect query response

### ISSUE THREAD

**Issue by DutchShadow** [sipa/bitcoin-seeder#83]
The DNS seeder runs and reports changes coming in on amount of DNS requests as well as having a lot of nodes found (.dump file checked and validated that it found good nodes) but it doesn't answer the requests properly.

**Comment by sipa** [comment]
That's very little information to go on. Can you elaborate on "doesn't answer requests properly" ? What did you try, what do you expect to see, what do you see instead?

**Comment by DutchShadow** [comment]
Thanks for the very quick response,
A dig command with a trace shows it finds the server but ends with a warming that the query response is not set

**Comment by DutchShadow** [comment]
Seeder status:
```
Loading dnsseed.dat...done
Starting 4 DNS threads for eudns1.xxxx.net on dnsseed2.xxxx.com (port 53).......done
Starting seeder...done
Starting 96 crawler threads...done
[20-03-15 10:18:25] 1800/2716 available (2493 tried in 999s, 0 new, 223 active), 257 banned; 209 DNS requests, 4 db queries
```

End of a Dig with a `+trace`:
```
dnsseed2.xxxx.com. 300 IN      NS      eudns2.xxxx.net.
;; Received 89 bytes from 173.245.58.85#53(chloe.ns.cloudflare.com) in 13 ms

;; Warning: query response not set
;; Received 12 bytes from 81.2.x.207#53(eudns2.xxxx.net) in 35 ms
```
Digs increase the amount of DNS requests
