### ISSUE TITLE
Whate exacly is BITCOIN_SEED_NONCE and where it came from?

### ISSUE THREAD

**Issue by kodxana** [sipa/bitcoin-seeder#93]
Do anyone know where that value came from in Bitcoin source?
https://github.com/sipa/bitcoin-seeder/blob/a09d2870d1b7f4dd3c1753bbf4fd0bc3690b7ef9/bitcoin.cpp#L9

**Comment by sipa** [comment]
It's just an arbitrary 64-bit number.

The version message contains a nonce to detect if a node is connected to itself. Bitcoin Core sends a random number here, and sees if it receives the same number back.

The seeder doesn't have that risk (it doesn't accepting incoming connections) so it just uses a fixed value.

**Comment by kodxana** [comment]
> It's just an arbitrary 64-bit number.
> 
> The version message contains a nonce to detect if a node is connected to itself. Bitcoin Core sends a random number here, and sees if it receives the same number back.
> 
> The seeder doesn't have that risk (it doesn't accepting incoming connections) so it just uses a fixed value.

Thanks for information. I also tried to setup own seed node but I'm kinda stuck with DNS. I have setup A and NS record corectly but trying do dig domain gives nothing even when node has file with good nodes.
```
35/111 available (0 tried in 2023s, 0 new, 111 active), 0 banned; 0 DNS requests, 0 db queries
```
